name = "FeatureSelector"
uuid = "e0e7d8aa-9f8d-4d2b-94aa-a22ac5d6b31b"
authors = ["Darren Lukas <darrenc2995@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
