name: Test
on:
  push: 
    branches:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter
    - /^release-.*$/ # Release branches, if any.
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@master
      - uses: julia-actions/julia-runtest@master
      - name: "Coverage"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
        run: julia -e '
             using Pkg;
             Pkg.add("Coverage");
             using Coverage;
             Codecov.submit(process_folder());'
        shell: bash
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl