name: Test
on:
  push: 
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter
    - /^release-.*$/ # Release branches, if any.
  pull_request:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [stable, lts]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@master
      - uses: julia-actions/julia-runtest@master
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: stable
      - uses: julia-actions/julia-buildpkg@master
      - name: "Documentation"
        run: julia --project=docs -e '
             using Pkg;
             Pkg.develop(PackageSpec(; path=pwd()));
             Pkg.instantiate();
             include("docs/make.jl");'
        shell: bash
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: stable
      - uses: julia-actions/julia-buildpkg@master
      - name: "Coverage"
        run: julia -e '
             using Pkg;
             Pkg.add("Coverage");
             using Coverage;
             Codecov.submit(process_folder());'
        shell: bash